### ISSUE TITLE
I want to go where to submit Chinese language text?

### ISSUE THREAD

**Issue by SilenceDuan** [BinaryCPG/MM#1]
I made Chinese language text.
zh_CN.lang

**Comment by BinaryCPG** [comment]
Just send me an email with the file attachted to binarycpg@gmail.com; then ill implement it :D

**Comment by SilenceDuan** [comment]
@BinaryCPG 
Thank you, I will be sent to your email address.
We have to reflect the server game player, a currency exchange machine is not convenient, coins with take up a lot of space in the body, want to consider adding a purse?

**Comment by BinaryCPG** [comment]
I'll take a look if I can implement a purse as soon as possible.

**Comment by SilenceDuan** [comment]
Thank you very much!
I will help you to improve your Money mod let it be all servers choose as far as possible!
