### ISSUE TITLE
RF as energy for the Money Exchanger

### ISSUE THREAD

**Issue by medsal15** [BinaryCPG/MM#2]
EUs are used only by IC2 (of all the mod I know) and its addons. MJs are dead because BC moved to RF. RFs are used by the 75-90% of the other mods with energy.
For the total I think it's like: 75% RF, 15% EU, 5% other.

**Comment by BinaryCPG** [comment]
Just adding that :D

**Comment by BinaryCPG** [comment]
RF is added in code, wait till version 1.3 is realeased:D
